# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run MCMC
#'
#' Fits a binomial model to well count data. Uses Metropolis-Hastings MCMC to generate samples from the posterior distribution of IUPM.
#'
#' @param nPos number of positive wells
#' @param nWells total number of wells for each dilution
#' @param dilFrac dilution fractions
#' @param nChains number of chains
#' @nBurnin number of burn-in iterations
#' @nSample number of sampling iterations
#'
#' @return A list containing chains of IUPM values, a vector of chain IDs, and a vector of acceptance rates
#'
#' @export
runSampler <- function(nPos, nWells, dilFrac, nChains, nBurnin, nSample) {
    .Call(`_BayesQLD_runSampler`, nPos, nWells, dilFrac, nChains, nBurnin, nSample)
}

