// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// testLP
double testLP(const std::vector<double>& nPos, const std::vector<double>& nWells, const std::vector<double>& dilFrac, const double& theta);
RcppExport SEXP _BayesQLD_testLP(SEXP nPosSEXP, SEXP nWellsSEXP, SEXP dilFracSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type nPos(nPosSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type nWells(nWellsSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type dilFrac(dilFracSEXP);
    Rcpp::traits::input_parameter< const double& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(testLP(nPos, nWells, dilFrac, theta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesQLD_testLP", (DL_FUNC) &_BayesQLD_testLP, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesQLD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
